version: '3'

services:
  src:
    build: 
      context: src
    ports:
      - "5050"
  nginx:
    image:  nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - src
    ports:
      - "5050:5050"
